version = 0.1
[default.deploy.parameters]
stack_name = "api-stay-smart"
resolve_s3 = true
s3_prefix = "api-stay-smart"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
